#pragma once
/**
* creator: Kiet Duong
* date: 2017-02-06
* file: ResultCodeConstant.h
*/
#define RESULT_CODE_VALID  0
#define RESULT_CODE_USER_NOT_HAVE_PERMISSION  -1
#define RESULT_CODE_TOKEN_EXPIRED  -456
#define RESULT_CODE_EMAIL_POLICY_ERROR  -999
#define RESULT_CODE_NETWORK_TIME_OUT  408
#define RESULT_CODE_NETWORK_ERROR  404

#define RESULT_CODE_INVALID  -1000
#define RESULT_CODE_NOT_LOGIN  -1001
#define RESULT_CODE_NO_PERMISSION  -1002
#define RESULT_CODE_ACCESS_TOKEN_EXPIRED  -1003
#define RESULT_CODE_FB_TOKEN_UNAUTHORIZED  -1004
#define RESULT_CODE_EMPTY_STRING  -1005
#define RESULT_CODE_INVALID_VERSION  -1006
#define RESULT_CODE_FUNCTION_DISABLE  -1007
#define RESULT_CODE_INVALID_COINS  -1008
#define RESULT_CODE_NOT_TIME_YET  -1009
#define RESULT_CODE_GIFT_ALREADY_ACCEPTED  -1010
#define RESULT_CODE_UNAVAILABLE_SERVER_CONFIG  -1050
#define RESULT_CODE_INVALID_FACEBOOK_ID  -1060
#define RESULT_CODE_INVALID_TARGET_USER_ID  -1070
#define RESULT_CODE_SERVER_FILE_ERROR  -1100
#define RESULT_CODE_SEND_GIFT_TYPE_NON_SUPPORT  -1101
#define RESULT_CODE_ACCEPT_GIFT_TYPE_NON_SUPPORT  -1102
#define RESULT_CODE_INVALID_GIFT_TYPE  -1103

/* Chỉ dùng để check các result code đặc biệt */
#define RESULT_CODE_OK  -99999

#define RESULT_CODE_SERVER_MAINTENANCE  -1200
#define RESULT_CODE_FORCE_USER_RELOAD  -1300

#define RESULT_CODE_VOUCHER_EXPIRED  -1400

#define RESULT_CODE_USER_REJECTED_APP  -1500

#define RESULT_CODE_USER_REDEEM_VOUCHER_ALREADY  -1600

/* Wallet */
#define WALLET_RESULT_CODE_EXCEPTION_OCCURRED_WHILE_CALLING_WALLET_SERVER  -2000
#define WALLET_RESULT_CODE_INVALID_AMOUNT  -2001
#define WALLET_RESULT_CODE_INVALID_CURRENCY  -2002

#define RESULT_CODE_USER_NOT_EXIST  -4000
#define RESULT_CODE_USER_BAN  -4001
#define RESULT_CODE_USER_NOT_ACTIVATE  -4002
#define RESULT_CODE_USER_EXIST  4000
#define RESULT_CODE_USER_ACTIVATED  4002
#define RESULT_CODE_USER_NOT_GUEST  4004

#define RESULT_CODE_EMAIL_EXIST  5000
#define RESULT_CODE_PASSWORD_POLICY_ERROR  -5000
#define RESULT_CODE_INVALID_PASSWORD  -5001
#define RESULT_CODE_RESET_PASSWORD_TOKEN_EXPIRED  -5500

#define RESULT_CODE_USER_LOGIN_IN_ANOTHER_LOCATION  -6000

#define RESULT_CODE_DEPRECATED_API  -7000

#define RESULT_CODE_MERCHANT_NOT_ALLOWED  -8000

#define RESULT_CODE_MERCHANT_IP_INVALID  -8500

#define RESULT_CODE_FACEBOOK_ERROR  -9000

#define RESULT_CODE_DATE_INVALID  -9100
#define RESULT_CODE_TIME_CALL_INVALID  -9101

#define RESULT_CODE_NON_SUPPORT_START_DATE  -9200

#define RESULT_CODE_CAN_NOT_DECRYPT_TEXT  -10000
#define RESULT_CODE_PAYMENT_EXIST  -10001
#define RESULT_CODE_INVALID_PRODUCT_ID  -10002
#define RESULT_CODE_VERIFY_GOOGLE_RECEIPT_FAIL  -10003
#define RESULT_CODE_INVALID_APP_ID  -10004
#define RESULT_CODE_ERROR_CODE_FROM_GOOGLE_SERVER  -10005
#define RESULT_CODE_ERROR_CODE_FROM_APPLE_SERVER  -10006
#define RESULT_CODE_INVALID_PRODUCT_TYPE  -10007
#define RESULT_CODE_INVALID_PAYMENT_API_VERSION  -10008
#define RESULT_CODE_INVALID_PAYMENT_DATA  -10009
#define RESULT_CODE_FACEBOOK_CHARGE_FAILED  -10010
#define RESULT_CODE_UNSUPPORTED_PRODUCT  -10011

#define RESULT_CODE_INVALID_CIDR_NOTATION  -11000
#define RESULT_CODE_INVALID_MERCHANT_ID  -11500

#define RESULT_CODE_NO_COMEBACK_BONUS  -12000

#define RESULT_CODE_SPIN_TOO_FAST  -13000

// 2015-12-30: Phuoc: dùng khi update name/avatar, chỉ có user loại username/password mới được update name/avatar
#define RESULT_CODE_INVALID_USER_TYPE  -14000
#define RESULT_CODE_INVALID_FILE_TYPE  -15000

#define RESULT_CODE_INVALID_IMAGE_DIMENSION  -16000

#define RESULT_CODE_FORCE_CLIENT_UPDATE_APP_LOBBY  -17000

#define RESULT_CODE_INVALID_VOUCHER_TOKEN  -18000

#define RESULT_CODE_NOT_ENOUGH_CROWN_TO_UNLOCK_SLOT_GAME  -19000
#define RESULT_CODE_NOT_ENOUGH_LEVEL_TO_UNLOCK_SLOT_GAME  -20000

#define RESULT_CODE_INCOMPLETE_ACHIEVEMENT  -21000
#define RESULT_CODE_ACHIEVEMENT_IS_ALREADY_COLLECTED  -22000
#define RESULT_CODE_NOT_GUEST_USER  -23000
#define RESULT_CODE_LEVEL_EXIST  -24000

// 2016-03-05: Ty:
#define RESULT_CODE_EXCEED_MAX_NUMBER_OF_TIME_CHANGE_NAME  -25000

// 2016-03-11: Phuoc:
#define RESULT_CODE_TUTORIAL_REWARD_IS_ALREADY_REDEEMED  -26000

//03-21-2016: Dac
#define RESULT_CODE_INVALID_RESOURCE_VERSION  -27000

// 2016-04-05: Toan
#define RESULT_CODE_FAIL_TO_CHECK_HMAC  -28000
#define RESULT_CODE_FAIL_TO_SAVE  -29000
#define RESULT_CODE_INTERNAL_SERVER_ERROR  -30000
#define RESULT_CODE_FAIL_TO_PARSE_USER_ID  -31000


// 2016-04-11: Toan
#define RESULT_CODE_TRANSACTION_ID_EXIST  -32000
#define RESULT_CODE_WRONG_PLATFORM  -33000

// 2016-04-28: Toan
#define RESULT_CODE_NOT_ALLOW_GET_PRE_TUTORIAL_REWARD  -34000

#define RESULT_CODE_API_TOKEN_INVALID  -41000
#define RESULT_CODE_API_TOKEN_IS_EXPIRED  -42000

#define RESULT_CODE_EMAIL_NOT_EXIST  -50001
#define RESULT_CODE_SLOT_GAME_UNLOCKED  -50002

/* -------------------------------------------------- Strategy -------------------------------------------------- */
#define RESULT_CODE_DAILY_BONUS_STREAK_IS_ALREADY_COLLECTED  -60000

#define RESULT_CODE_FREE_COIN_GIFT_NOT_READY  -60010

#define RESULT_CODE_ALREADY_SEND_GIFT_FROM_REFERENCE_CODE  -60020
#define RESULT_CODE_REFERENCE_CODE_NOT_EXIT  -60021
#define RESULT_CODE_REFERENCE_CODE_MAX_TIME_REFER  -60022
#define RESULT_CODE_REFERENCE_CODE_YOUR_OWN_CODE  -60023

#define RESULT_CODE_DAILY_BONUS_LUCKY_SPIN_IS_ALREADY_COLLECTED  -60030

#define RESULT_CODE_NOT_ENOUGH_LEVEL_TO_USE_THIS_FEATURE  -60040

#define RESULT_CODE_INVALID_QUANTITY_OF_SPIN_FOR_LUCKY_WHEEL  -60050
#define RESULT_CODE_NOT_ENOUGH_CROWN_TO_BUY_SPIN_OF_LUCKY_WHEEL  -60051

#define RESULT_CODE_INVALID_LUCKY_BOX_TYPE  -60060
#define RESULT_CODE_INVALID_QUANTITY_LUCKY_BOX  -60061

#define RESULT_CODE_TYPE_LEADER_BOARD_NON_SUPPORT  -60070

#define RESULT_CODE_TYPE_DAILY_CHALLENGE_REWARD_IS_ALREADY_COLLECTED  -60080
#define RESULT_CODE_TYPE_DAILY_CHALLENGE_IS_INCOMPLETE  -60081

#define RESULT_CODE_COMEBACK_BONUS_MOBILE_REWARD_IS_NOT_READY  -60090

#define RESULT_CODE_INVALID_MAGIC_ITEM_TYPE  -60100
#define RESULT_CODE_INVALID_SIMULATOR_API_TYPE  -60110

#define RESULT_CODE_UNSUPPORTED_FEATURE  -60200

#define RESULT_CODE_INVALID_SERVER_ROLE  -60300
/* -------------------------------------------------- Strategy -------------------------------------------------- */