#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCREEN 2.5
#define TRANSITION_TIME 0.5
#define ENEMY_SPAWN_FREQUENCY 1

#define PIPE_GAP 10
#define UPPER_SCREEN_PIPE_THRESHOLD 0.65
#define LOWER_SCREEN_PIPE_THRESHOLD 0.35

#define PIPE_MOVEMENT_SPEED 0.01

#define PLAYER_COLLISION_BITMASK_PLAY 0x000001
#define BOUND_COLLISION_BITMASK 0x000002
#define OBSTACLE_COLLISION_BITMASK 0x000003
#define POINT_COLLISION_BITMASK 0x000004
#define GOURND_COLLISION_BITMASK_PLAY 0x000005
#define OBSTACLE_GOBACK_COLLISION_BITMASK 0x000006

#define EXTRA_HEIGHT 14
#define SQUARE_SIZE 30
#define FLOOR_WIDTH 800
#define FLOOR_HEIGHT 20
#define LEVEL_HEIGHT 100
#define SQUARE_SIZE 30
#define SQUARE_SPEED 200
#define SQUARE_GRAVITY 450
#define JUMP_FORCE -210
#define JUMP_TIME 0.1
#define HEIGHT_OF_LEG_OF_SQUARE 30

#define SCORE_FONT_SIZE 0.05

#define CACHE_MAX_SCORE "cache_max_score"
#define CACHE_CAN_PLAY_MUSIC "cache_can_play_music"


#endif // __DEFINITIONS_H__
